### ISSUE TITLE
Cannot Pass JSON as part of POST request

### ISSUE THREAD

**Issue by EllieSky** [peritus/robotframework-httplibrary#12]
I am using HttpLibrary.HTTP to test REST api.

I am authenticating as a user, retrieving the token, and then I want to update the user's password. This last part, requires me to execute a POST, where I pass JSON as a container of 2 parameters.

Here is what it looks like in firebug:

```
{"oldPassword":"rest123","password":"REST123"}
```

Here is my test:

```
REST Change User Password
    [Arguments] ${token}  ${oldPassword}  ${newPassword}  ${tenant}=${REST_TENANT}
    Create Http Context ${endpoint} https
    Set Request Header  Cookie  RAPToken=${token}
    ${dict}=    Create Dictionary  oldPassword  ${oldPassword}  password  ${newPassword}
    ${value}=   Stringify Json  ${dict}
    Set Request Body    ${dict}
//# I have also tried:
//# Set Request Body    ${value}
    POST    ${uri_auth_user}?&RAPTenant=${tenant}
```

If I pass a dictionary ${dict} I get: AttributeError: 'dict' object has no attribute 'encode'
If I pass Stringify Json value ${value} I get: 415 Unsupported Media Type

Am I doing it wrong? Or is there simply no way to pass JSON.
Also is there a way to retrieve JSON that got passed back as part of the response?

I've googled and searched, and even looked at the source code for this library, but I simply cannot figure out how to pass json. Please help.

Otherwise, this library has been very useful and reliable. Many thanks.

**Comment by peritus** [comment]
Thanks for using this library!

First, you can use `-L TRACE` when invoking Robot Framework to get a detailed log of what is transmitted via HTTP.

Second, `Set Request Body    ${value}` looks about right, as the library intentionally doesn't contain any automagic that converts dicts to JSON.

Third, `415 Unsupported Media Type` looks like an error sent by your http server, so the request gets through but is rejected by your server. You might want to look at the `Content-Type` and `Accept` headers in firebug and set these in the test as well.

**Comment by peritus** [comment]
Regarding a json response:

```
${result_text}=        Get Response Body
${result_json}=        Parse Json    ${result_text}
```

works for me.

**Comment by EllieSky** [comment]
Thank you for your response, it was tremendously helpful to me.
After setting the Content-Type header as you recommended, my test immediately started working!
Your other two recommendations were also very useful.
