### ISSUE TITLE
Pass string argument as a part of request url?

### ISSUE THREAD

**Issue by chy168** [peritus/robotframework-httplibrary#20]
Hi,
I would like to write a common function which composited by httplibrary.
The keyword as below:

```
Get Test Account
    [Arguments]  ${req name}
    Create Http Context  localhost  http
    GET  /account?name=${req name}
```

In my test, does it seems not parse by RF ? I will send the raw string
`/account?name=${req name}`
 to server. Is that a problem i use the argument and string in GET request?

Andy idea about this prolblem?

I also come up  a workaround by Catenate.

```
Get Test Account
    [Arguments]  ${req name}
    Create Http Context  localhost  http
    ${new url}  Catenate  SEPARATOR=  /account?name=  ${req name}
    GET  ${new url}
```

Thanks!

**Comment by peritus** [comment]
I have no idea, both examples look like valid RF to me, but I could also be wrong. Parsing the robot-files is done by RF, unfortunately there is nothing i can do about this in this library.
