### ISSUE TITLE
Not possible to init using maven plugin

### ISSUE THREAD

**Issue by stupchiy** [peritus/robotframework-httplibrary#25]
Trying to use library within Maven Plugin - http://robotframework.org/MavenPlugin/index.html, using extraPathDirectories to load properly PYTHONPATH, library itself loaded by maven... but have this error in related to HTTPLibrary other libraries...

Getting error on related library webtest==2.0.7

```
[ ERROR ] Error in file '/Users/username/test/test.txt': Importing test library 'HttpLibrary.HTTP' failed: SyntaxError: no viable alternative at input ''----------a_BoUnDaRy'' (app.py, line 331)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/HttpLibrary/__init__.py", line 7, in <module>
    import livetest
  File "/usr/local/lib/python2.7/site-packages/HttpLibrary/livetest.py", line 42, in <module>
    import webtest
  File "/usr/local/lib/python2.7/site-packages/webtest/__init__.py", line 9, in <module>
    from webtest.app import TestApp
```

Is this related to HTTPLibrary or not and do you have any idea how to solve this? 
Sorry if it's not related, just can't find any solution in internet

P.S.: Using only pybot, it is working... maybe problem since I'm trying to use it from JAVA side, but has no such problem with other library (e.g. DatabaseLibrary)

**Comment by peritus** [comment]
Using this library from Java should work, but I don't have the expertise in debugging it.

You can try whether `import webtest` works on the jython command line, and maybe file a bug with webtest (although I don't know if jython is in their list of supported platforms).

**Comment by peritus** [comment]
Thinking about it, `SyntaxError: no viable alternative at input ''----------a_BoUnDaRy'' (app.py, line 331)` looks like a multipart message (http://www.w3.org/Protocols/rfc1341/7_2_Multipart.html) — how did you download webtest ? Please install via `pip`, that could solve this.

**Comment by stupchiy** [comment]
Hi Thanks, for the replies,
Yes I have installed using "pip", and tried also different versions...
And you right as to jython cmd, the same issue. And still can't manage to work it out.
I asked in webtest related google-group, maybe they will have some suggestion

**Comment by stupchiy** [comment]
Hi, just wanted to comment out with a solution, in case you will need it at some point:
First of all the issue was due to jython 2.5 version, since it's replicate python 2.5 and the functions used in webtest library are supported only from 2.6 (actually just used differently, as I understood). So to solve this you need to use jython 2.7, which is currently in beta and so, not included in usual robot jar, and I found very helpful solution in robot google group, how to include newer jython version:
https://groups.google.com/forum/#!msg/robotframework-devel/Ty4mJVP8_l8/zNdVfpadXNsJ
Thanks, for the time and answers

**Comment by peritus** [comment]
You're welcome. Glad I could help.

Have fun using my software and report back if there's anything I can do to make it even more fun!

**Comment by peritus** [comment]
@stupchiy Did you make this library work in jython eventually ? Asking for a friend.

**Comment by stupchiy** [comment]
Hey @peritus, sorry for late reply, yes I have managed to make it running... to solve this look to description above. If you will need some additional help let me know
