### ISSUE TITLE
Library Should Support Virtual Hosting

### ISSUE THREAD

**Issue by johngluck65** [peritus/robotframework-httplibrary#3]
Steps to Reproduce
This needs to be on server that is set up to support virtual hosting

For example: http://httpd.apache.org/docs/2.0/vhosts/examples.html
1. Create HTTP Context with www.myfirstdomain.com (This apparently sets the Host: resquest header)
2. Now do a GET on http://www.myseconddomain.com

Expected
- Examining the location response header should show www.myfirstdomain.com

Actual
- The location response header shows www.myseconddomain.com (or if it's a 302 where ever it was redirected to).  This is because the call to get appears to be replacing the Host: request header with www.myseconddomain.com.  It should only do this if the Host:request header is not already set.  Note also that livetest seems to explicitly prevent setting the Host: request header.  I don't really understand why it's doing this.

**Comment by peritus** [comment]
So, here's what you do:

```
Set HTTP Host                 www.myfirstdomain.com
Set Request Header            Host                          www.myseconddomain.com
GET                           /path/without/hostname
```

There was an unneccessary (if you ask me) check in livetest (that I'm using underneath) that prevented this from working in the first place.

**Comment by peritus** [comment]
Reported upstream at https://github.com/storborg/livetest/issues/7 — and pushed to PyPI as v0.3.1 http://pypi.python.org/pypi/robotframework-httplibrary/0.3.1

**Comment by johngluck65** [comment]
Cool. Thanks
