### ISSUE TITLE
Robot framework: Multipart form parse error - Invalid boundary in multipart

### ISSUE THREAD

**Issue by dipakbachhav** [peritus/robotframework-httplibrary#54]
Create Session          img     http://myimage.org
    ${headers}=          Create Dictionary    Content-Type =multipart/form-data
    ${params} =          Create Dictionary      access_key_id=${access_key_id}
    ${file_data}=       Get Binary File     C:\Users\User\Downloads\Test1.png  
    &{data}=            Create Dictionary  file=${file_data}
    ${URI}=              Set Variable    /sampleuri/
    ${response}=         Post Request       img    ${URI}   data=${data}  params=${params}    headers=${headers}      timeout=5
    [return]            ${response}

Getting "post response: {"detail":"Multipart form parse error - Invalid boundary in multipart: None"}" error while trying to upload file to post api using robot framework. I am new to robot framework . Please help me with upload functionality for api. If you hav different example I am Ok with it. If you have any other example which explain how to upload images using post api & robot framework.

**Comment by seymafirat** [comment]
hello, can you find any solution for this?
