### ISSUE TITLE
HEAD request don't allow me to set request headers

### ISSUE THREAD

**Issue by johngluck65** [peritus/robotframework-httplibrary#6]
I've looked at my outgoing request with wireshark.  I am doing the following

Set Request Header  User-Agent  _censored_
HTTPLibrary.HTTP.HEAD   ${/}${file_path}

Server configuration should cause a custom response header to return

This does work if I change the request type to a GET

however when I look at my outgoing request, my request doesn't contain the User-Agent header that I am attempting to set

**Comment by peritus** [comment]
This is fixed included in v0.3.2, happy testing!
