### ISSUE TITLE
httplibrary is red after installing successfully

### ISSUE THREAD

**Issue by HoangHo16** [peritus/robotframework-httplibrary#65]
Please help. 
After httplibrary is installed successfully, I add this library to use but it's red.
Other libraries are fine, just issue in httplibrary.
Not sure why, please help me on this.
More info: httplibrary 0.4.2, RIDE 1.7.4.1dev running on Python 3.7.4. 
 
Thanks,
Hoang
![httplibrary](https://user-images.githubusercontent.com/59380452/71608286-ac1d5d00-2bb2-11ea-8b1a-671170bf546d.png)

**Comment by mattias-elvaco** [comment]
It's not py3 compatible

**Comment by HoangHo16** [comment]
Oh thanks Mattias. I'm using RequestLibrary instead.
